name: Docker CI/CD

on:
  push:
    branches:
      - test-docker-push # Trigger on pushes to the 'test-docker-push' branch

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile (current directory)
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ekart.cart.api:latest # Replace 'your-image-name'
          # Add more tags if needed, e.g., ${{ github.sha }} for commit SHA
